baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Studenti Unitelma'
theme = 'hugo-book'

enableEmoji = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  style = 'base16-snazzy'

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  languageName = 'Italiano'
  contentDir = 'content'
  weight = 1

[menu]
[[menu.home]]
  name = 'Documentation'
  pageRef = '/docs/example/'
  weight = 1

[[menu.home]]
  pageRef = '/docs/example/'
  weight = 10
  parent = 'Documentation'

[[menu.home]]
  name = 'Shortcode'
  pageRef = '/docs/shortcodes/buttons/'
  weight = 20
  parent = 'Documentation'

[[menu.home]]
  name = 'Showcase'
  pageRef = '/showcases/'
  weight = 2
